export const wifiEditorialRedirects = [
  { source: "/blog", destination: "/planos-de-internet" },
  { source: "/comparar", destination: "/planos-de-internet" },
  { source: "/internet-residencial", destination: "/planos#pacotes" },
  { source: "/celular-e-internet", destination: "/planos#internet-celular" },
  { source: "/tv-e-streaming", destination: "/planos#tv-streaming" },
  { source: "/operadoras", destination: "/planos#operadoras" },
  { source: "/operadoras/claro", destination: "/planos#operadora-claro" },
  { source: "/operadoras/vivo", destination: "/planos#operadora-vivo" },
  { source: "/operadoras/tim", destination: "/planos#operadora-tim" },
  { source: "/contratacao", destination: "/planos-de-internet" },
  { source: "/velocidades", destination: "/planos-de-internet" },
  { source: "/guias-de-operadoras", destination: "/planos-de-internet" },
  { source: "/comparacoes-e-combos", destination: "/planos-de-internet" },
  { source: "/wifi-e-uso", destination: "/wifi-e-fibra" },
  { source: "/silos/contratacao", destination: "/planos-de-internet" },
  { source: "/silos/velocidades", destination: "/planos-de-internet" },
  { source: "/silos/guias-de-operadoras", destination: "/planos-de-internet" },
  { source: "/silos/comparacoes-e-combos", destination: "/planos-de-internet" },
  { source: "/silos/wifi-e-uso", destination: "/wifi-e-fibra" },
  { source: "/blog/planos-de-internet/:path*", destination: "/planos-de-internet/:path*" },
  { source: "/planos/500-mega", destination: "/planos-de-internet" },
  { source: "/planos/600-mega", destination: "/planos-de-internet" },
  { source: "/planos/1-giga", destination: "/planos-de-internet" },
];
